openapi: 3.0.0
info:
  version: 1.0.0
  title: "8282 API docs"
  description: "Elice SW3 Team 8282 API 문서"
  license:
    name: KJ
servers:
  - url: http://localhost:3003/
paths:
  /api/main/auth/email:
    $ref: "./auth.yaml#/~1auth~1email"
  /api/main/auth/certify:
    $ref: "./auth.yaml#/~1auth~1certify"
  /api/main/auth/join:
    $ref: "./auth.yaml#/~1auth~1join"
  /api/main/auth/login:
    $ref: "./auth.yaml#/~1auth~1login"
  /api/main/auth/{email}:
    $ref: "./auth.yaml#/~1auth~1{email}"
  /api/main/auth/delete:
    $ref: "./auth.yaml#/~1auth~1delete"
  /api/main/auth/update:
    $ref: "./auth.yaml#/~1auth~1update"
  /api/main/auth/refresh:
    $ref: "./auth.yaml#/~1auth~1refresh"
  /api/main/comment:
    $ref: "./comment.yaml#/~1comment"
  /api/main/comment/{commentId}:
    $ref: "./comment.yaml#/~1comment~1{commentId}"
  /api/main/communities:
    $ref: "./communities.yaml#/~1communities"
  /api/main/communities/{communityId}:
    $ref: "./communities.yaml#/~1communities~1{communityId}"
  /api/main/communities/community:
    $ref: "./communities.yaml#/~1communities~1community"
  /api/main/likes:
    $ref: "./likes.yaml#/~1likes"
  /api/main/likes/like:
    $ref: "./likes.yaml#/~1likes~1like"
  /api/main/matches/match:
    $ref: "./matches.yaml#/~1matches~1match"
  /api/main/matches/{matchId}:
    $ref: "./matches.yaml#/~1matches~1{matchId}"
  /api/main/mypage:
    $ref: "./mypage.yaml#/~1mypage"
  /api/main/mypage/comments:
    $ref: "./mypage.yaml#/~1mypage~1comments"
  /api/main/mypage/myEnroll:
    $ref: "./mypage.yaml#/~1mypage~1myEnroll"
  /api/main/mypage/receivedEnroll:
    $ref: "./mypage.yaml#/~1mypage~1receivedEnroll"
  /api/main/mypage/posts:
    $ref: "./mypage.yaml#/~1mypage~1posts"
  /api/main/notices:
    $ref: "./notices.yaml#/~1notices"
  /api/main/notices/{noticeId}:
    $ref: "./notices.yaml#/~1notices~1{noticeId}"
  /api/main/posts:
    $ref: "./posts.yaml#/~1posts"
  /api/main/posts/{postId}:
    $ref: "./posts.yaml#/~1posts~1{postId}"
  /api/main/posts/post:
    $ref: "./posts.yaml#/~1posts~1post"
  /api/main/search:
    $ref: "./search.yaml#/~1search"
  /api/admin/notices/{noticeId}:
    $ref: "./admin.yaml#/~1notices~1{noticeId}"
  /api/admin/notices/notice:
    $ref: "./admin.yaml#/~1notices~1notice"
  /api/admin/users:
    $ref: "./admin.yaml#/~1users"
  /api/admin/users/{email}:
    $ref: "./admin.yaml#/~1users~1{email}"
components:
  schemas:
    status:
      type: object
      properties:
        200번대:
          type: object
          description: 성공 응답
          properties:
            200:
              description: "요청 성공<br>클라의 요청을 무사히 처리했을 때 발생<br>데이터가 추가되지 않는 POST를 포함한 대부분의 method에서 뜸"
            201:
              description: "데이터 생성 완료<br>클라의 요청을 무사히 처리했을 때 발생<br>POST 요청시 뜰 수 있음"
            204:
              description: "요청은 처리됐으나 내용이 없음<br>DB에 등록된 데이터가 없을 때 발생<br>보통 GET 요청시 뜰 수 있음"
        400번대:
          type: object
          description: 클라 에러 응답
          properties:
            400:
              description: "잘못된 요청<br>요청과 함께 넘어온 정보가 옳지 않을 때 발생<br>이메일 인증 번호가 틀렸거나, 로그인시 이메일이나 비밀번호가 틀리면 뜸"
            401:
              description: "인증되지 않음<br>인증된 토큰이 아닐 때 발생<br>acess가 없거나 만료됐거나 훼손됐거나, refresh가 만료됐거나 값이 다르면 뜸"
            403:
              description: "권한이 없음<br>클라가 허용되지 않은 api를 요청할 때 발생<br>인증되지 않은 이메일이 회원가입을 요청하면 뜸"
            404:
              description: "정보 없음<br>없는 api를 요청할 때 발생<br>사용되지 않는 uri로 접근하면 뜸"
            409:
              description: "충돌 <br> 이미 가입된 이메일로 회원가입을 시도하면 뜸"
        500번대:
          type: object
          description: 서버 에러 응답
          properties:
            500:
              description: 기타 에러
    comment:
      properties:
        commentId:
          type: string
          description: 댓글 id
        author:
          type: object
          description: 댓글 작성자
          properties:
            email:
              type: string
            nickname:
              type: string
            profileImg:
              type: String
        content:
          type: string
          description: 댓글 내용
        communityId:
          type: string
          description: 자유게시글 id
        postId:
          type: string
          description: 동행게시글 id
    community:
      properties:
        communityId:
          type: string
          description: 자유게시글 id
        author:
          type: object
          description: 자유게시글 작성자
          properties:
            email:
              type: string
            nickname:
              type: string
            profileImg:
              type: String
        title:
          type: string
          description: 자유게시글 제목
        content:
          type: string
          description: 자유게시글 내용
        region:
          type: string
          description: 지역
        category:
          type: string
          description: 카테고리
        commentCount:
          type: string
          description: 댓글 수
    like:
      properties:
        email:
          type: string
          description: 좋아요 표시한 유저 이메일
        postId:
          type: string
          description: 좋아요 표시된 동행게시글 id
    match:
      properties:
        matchId:
          type: string
          description: 동행 신청 id
        postId:
          type: string
          description: 신청한 동행게시글 id
        author:
          type: object
          description: 동행게시글 작성자, 신청받은 유저
          properties:
            email:
              type: string
            nickname:
              type: string
            profileImg:
              type: String
        applicant:
          type: object
          description: 동행 신청한 유저
          properties:
            email:
              type: string
            nickname:
              type: string
            profileImg:
              type: String
        status:
          type: string
          description: 대기중/수락/거절
    notice:
      properties:
        noticeId:
          type: string
          description: 공지사항 id
        title:
          type: string
          description: 공지사항 제목
        content:
          type: string
          description: 공지사항 내용
    post:
      properties:
        postId:
          type: string
          description: 동행게시글 id
        author:
          type: object
          description: 동행게시글 작성자
          properties:
            email:
              type: string
            nickname:
              type: string
            profileImg:
              type: String
        title:
          type: string
          description: 동행게시글 제목
        content:
          type: string
          description: 동행게시글 내용
        region:
          type: string
          description: 지역
        thumbnail:
          type: string
          description: 동행게시글 썸네일
        duration:
          type: array
          items:
            type: string
          description: 여행기간
        hopeGender:
          type: string
          description: 희망 성별
        hopeAge:
          type: array
          items:
            type: string
          description: 희망 나이
        userCount:
          type: number
          description: 최대 인원
        contact:
          type: string
          description: 작성자 연락처
        status:
          type: boolean
          description: 모집상태
    user:
      properties:
        email:
          type: string
          description: 이메일
        nickname:
          type: string
          description: 닉네임
        password:
          type: string
          description: 비밀번호
        gender:
          type: string
          description: 성별
        age:
          type: string
          description: 나이대
        introduce:
          type: string
          description: 자기소개
        profileImg:
          type: string
          description: 프로필 사진
        matchCount:
          type: number
          description: 동행 횟수
        matchPoint:
          type: number
          description: 동행 점수
        role:
          type: string
          description: 권한(user 또는 admin)
