openapi: 3.0.0
info:
  version: 1.0.0
  title: "8282 API docs"
  description: "Elice SW3 Team 8282 API 문서"
  license:
    name: KJ
servers:
  - url: http://localhost:5000/
paths:
  /api/main/auth/email:
    $ref: "./auth.yaml#/~1auth~1email"
  /api/main/auth/certify:
    $ref: "./auth.yaml#/~1auth~1certify"
  /api/main/auth/join:
    $ref: "./auth.yaml#/~1auth~1join"
  /api/main/auth/login:
    $ref: "./auth.yaml#/~1auth~1login"
components:
  schemas:
    status:
      type: object
      properties:
        200번대:
          type: object
          description: 성공 응답
          properties:
            200:
              description: "요청 성공<br>클라의 요청을 무사히 처리했을 때 발생<br>데이터가 추가되지 않는 POST를 포함한 대부분의 method에서 뜸"
            201:
              description: "데이터 생성 완료<br>클라의 요청을 무사히 처리했을 때 발생<br>POST 요청시 뜰 수 있음"
            204:
              description: "요청은 처리됐으나 내용이 없음<br>DB에 등록된 데이터가 없을 때 발생<br>보통 GET 요청시 뜰 수 있음"
        400번대:
          type: object
          description: 클라 에러 응답
          properties:
            400:
              description: "잘못된 요청<br>요청과 함께 넘어온 정보가 옳지 않을 때 발생<br>이메일 인증 번호가 틀렸거나, 로그인시 이메일이나 비밀번호가 틀리면 뜸"
            401:
              description: "인증되지 않음<br>인증된 토큰이 아닐 때 발생<br>acess가 없거나 만료됐거나 훼손됐거나, refresh가 만료됐거나 값이 다르면 뜸"
            403:
              description: "권한이 없음<br>클라가 허용되지 않은 api를 요청할 때 발생<br>인증되지 않은 이메일이 회원가입을 요청하면 뜸"
            404:
              description: "정보 없음<br>없는 api를 요청할 때 발생<br>사용되지 않는 uri로 접근하면 뜸"
            409:
              description: "충돌 <br> 이미 가입된 이메일로 회원가입을 시도하면 뜸"
        500번대:
          type: object
          description: 서버 에러 응답
          properties:
            500:
              description: 기타 에러
    user:
      properties:
        email:
          type: string
          description: 이메일
        nickname:
          type: string
          description: 닉네임
        password:
          type: string
          description: 비밀번호
        gender:
          type: string
          description: 성별
        age:
          type: string
          description: 나이대
        introduce:
          type: string
          description: 자기소개
        image:
          type: string
          description: 프로필 사진
        role:
          type: string
          description: 권한(user 또는 admin)
